image: node:22
deploy:
  script:
    - npm ci
    - npm build
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----" > id
    - echo "$secret" >> id
    - echo "-----END OPENSSH PRIVATE KEY-----" >> id
    - rsync --partial --recursive --verbose ./ www@chee.party:/srv/www/cherries/app/
    - ssh www@chee.party pm2 restart cherries
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
