image: node:22
deploy:
  before_script:
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----\n$secret\n-----END OPENSSH PRIVATE KEY-----" | ssh-add
    - mkdir -p ~/.ssh
    - echo "Host *" > ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - npm i -g pm2
    - pm2 deploy ecosystem.config.cjs production
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
